<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <!-- 添加你的项目依赖 -->
    <ProjectReference Include="..\SereinFlow.Library\SereinFlow.Library.csproj" />
    <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" PrivateAssets="all" />
  </ItemGroup>


  <PropertyGroup>
    <AssemblyName>SereinFlow.OpenCvLibrary</AssemblyName>
    <RootNamespace>SereinFlow.OpenCvLibrary</RootNamespace>
    <Version>1.0.2</Version>
    <!-- 指定输出目录，避免 publish 产生额外层级 -->
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <!--<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>-->
  </PropertyGroup>

  <!--编译并生成 ZIP-->
  <!--dotnet build -c Release-->
  <!--或指定运行时-->
  <!--dotnet build -c Release -r win-x64-->

  <Target Name="CreatePackage" AfterTargets="Build">
    <!-- 清理旧的临时目录 -->
    <RemoveDir Directories="$(IntermediateOutputPath)package" />
    <!-- 创建打包目录 -->
    <MakeDir Directories="$(IntermediateOutputPath)package\$(AssemblyName)-$(Version)" />
    <!-- 复制编译输出（排除 publish 文件夹） -->
    <ItemGroup>
    <BuildFiles Include="$(TargetDir)**\*" Exclude="$(TargetDir)publish\**\*;$(TargetDir)win-x64\**\*;$(TargetDir)win-x86\**\*;$(TargetDir)linux-x64\**\*;$(TargetDir)linux-arm64\**\*;$(TargetDir)osx-x64\**\*;$(TargetDir)osx-arm64\**\*" />
    </ItemGroup>
    <Copy SourceFiles="@(BuildFiles)"
          DestinationFiles="@(BuildFiles->'$(IntermediateOutputPath)package\$(AssemblyName)-$(Version)\%(RecursiveDir)%(Filename)%(Extension)')"/>
    <!-- 打包 -->
    <ZipDirectory
      SourceDirectory="$(IntermediateOutputPath)package"
      DestinationFile="$(MSBuildProjectDirectory)\$(AssemblyName)-$(Version).zip"
      Overwrite="true" />
    <!-- 清理 -->
    <RemoveDir Directories="$(IntermediateOutputPath)package" />
    <Message Text="包已生成：$(MSBuildProjectDirectory)\$(AssemblyName)-$(Version).zip" Importance="high" />
  </Target>

</Project>
